services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: nomadloops-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data-container:/data

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    restart: unless-stopped
    container_name: nomadloops-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data-container:/root/.ollama
    env_file:
      - ./backend/.env

volumes:
  redis-data-container:
  ollama-data-container: