version: "3.9"
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: nomadloops-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data-container:/data

volumes:
  redis-data-container: