repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.2
    hooks:
        # Run the linter.
      - id: ruff
        types_or: [ python, jupyter ]
        args: [ --fix, -q ]
      # Run the formatter.
      - id: ruff-format
        args: [ -q ]
        types_or: [ python, jupyter ]