[project]
name = "nomadloops"
version = "0.1.0"
description = "Nomad Loops Backend"
authors = [{ name="Stan", email="stanis.konnov@gmail.com" }]

[tool.poe.tasks]
run = "python3 -m app.main"
test = "pytest -v --cov=app --cov-report term-missing"
